dist: trusty
language: php

os:
  - linux

jobs:
  include:
    - php: 7.4
    - php: nightly
      env: NIGHTLY_BUILD=true
    - php: 7.4
      env: TYPE_CHECK=true

  allow_failures:
    - php: 7.4
      env: TYPE_CHECK=true

  fast_finish: true

install:
  - php --version
  - composer self-update
  - composer --version
  - if [[ $NIGHTLY_BUILD = 'true' ]]; then composer install --ignore-platform-reqs; else composer install; fi

script:
  - composer test:unit
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer cs:check; fi
  - if [[ $TYPE_CHECK = 'true' ]]; then composer type:check; fi

after_script:
  - if [[ $NIGHTLY != 'true' ]]; then composer code:coverage; fi
  - if [[ $TYPE_CHECK = 'true' ]]; then composer type:coverage; fi
