dist: trusty
language: php

os:
  - linux

php:
  - '7.4'
  - nightly

jobs:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer --version
  - composer install

script:
  - composer cs:check
  - composer type:check
  - composer test:unit

after_script:
  - composer type:coverage
  - composer code:coverage
